### ISSUE TITLE
Add hold key customization

### ISSUE THREAD

**Issue by jchang504** [jchang504/keeptabs#1]
Allow the user to customize the hold key (default right now is Escape) they use to activate KeepTabs hotkeys. This is crucial because different systems (Mac, Windows PC) use different keys for system shortcuts, and users may have custom key remappings.

We should start with allowing the user to choose from a predefined set of choices (dropdown menu on the options page) including at least Escape, Ctrl, Alt, Cmd, Super (Windows key).

**Comment by jchang504** [comment]
Surprisingly, running Chrome v58 on Linux, Chrome actually gives priority to our content script before its built-in shortcuts. I can set the hold key to Control and then ctrl+f launches my Facebook hotkey instead of opening up the find bar. Similarly overrides ctrl+p, ctrl+s, etc. However, it still performs any shortcuts not overridden by a hotkey (e.g. ctrl+w for my options). This suggests that the browser shortcuts are running as ordinary listeners at a lower priority than our content script. Strangely, I find that the ctrl+1, ctrl+2, etc. shortcuts to switch tabs are not working.

Of course, OS-level shortcuts are still not overridden, so the user has to choose their hold key wisely.

**Comment by carbon-steel** [comment]
When using the hold key as Option on a Mac, the hotkeys no longer work because the keyboard input that is received when you hold Option and then press 'f' is not the keycode for f, but the keycode for ƒ (which is the symbol you get when you press Option and f at the same time on a Mac). The same goes for all of the other characters.

**Comment by carbon-steel** [comment]
Not to say that Control shouldn't be an option for the hold key, but I have an OS function (window zoom) mapped to Control+f that prevents Chrome from being able to be triggered by that hotkey. Not a big deal though. People in my situation just need to use a different hold key.

**Comment by carbon-steel** [comment]
Just an idea, but maybe we should consider using: https://developer.chrome.com/extensions/input_ime to deal with the symbols that get printed when typing with the alt/option key held down.

EDIT: Never mind. The IME functionality is only for devices running Chrome OS.
