### ISSUE TITLE
hotkeys that involve more than one key stroke does not work properly

### ISSUE THREAD

**Issue by carbon-steel** [jchang504/keeptabs#17]
![image](https://cloud.githubusercontent.com/assets/7697639/24732752/d6e83cfc-1a40-11e7-9d02-fc102740fabf.png)

In my options, todoist.com is mapped to 't' and toggl.com is mapped to 'to'. However, when I press the hotkey 't', I get sent to toggl.com. Using 'to' does not do anything.

Perhaps the order of the hotkeys in the options page has something to do with it.

**Comment by jchang504** [comment]
I have an analogous setup and it works for me. You have to reload the extension (on chrome://extensions) _and_ reload any tabs for new hotkey changes to take effect, due to #3. Try this and close the issue if it works after that.

**Comment by carbon-steel** [comment]
Huh, I thought that I did reload it, but I guess I forgot. Alright, it was my mistake.
