### ISSUE TITLE
Differentiate between URL's that have the same domain name

### ISSUE THREAD

**Issue by carbon-steel** [jchang504/keeptabs#24]
I set the hotkey 'to' to "https://www.toggl.com/app" and the hotkey 'm' to "https://www.facebook.com/messages". When I use the hotkeys to construct a new tab, they take me to the correct URL's. However, if there is a tab that has the same domain name (but not the same path aka the rest of the URL), the extension will just take me to that tab, which is incorrect.

Ex: using hotkey 'm' would take me to the already open tab that has the URL 'https://www.facebook.com/' even though I want to open a new tab with the complete URL that I had set.

**Comment by jchang504** [comment]
This is not necessarily incorrect, but certainly the more specific matching is a useful behavior. But more general domain matching is useful too, e.g. when you do want to navigate to whichever Facebook page you happen to have open. I think we should redesign the hotkey configuration a little to add a field for what should be counted as a match for a given hotkey (note this is only when deduplicate is checked). So the entry in options would look something like:

Hotkey | Target URL | Deduplicate? [Matches]

Where the Matches input would only appear when Deduplicate is checked.

**Comment by carbon-steel** [comment]
Closing this issue was an accident
