### ISSUE TITLE
Implement exporting/importing hotkey settings to/from local file

### ISSUE THREAD

**Issue by carbon-steel** [jchang504/keeptabs#31]
I'm so tired of losing my hotkey settings every time I remove Keeptabs (which I do for dev reasons). We have got to have a way to save these to a local file and load the hotkeys from that file if they ever get erased.

**Comment by jchang504** [comment]
As discussed in person this afternoon, you can either reload the extension to test local changes or disable the extension to temporarily test anything without it, so you never have to actually remove it. So this isn't a problem either for a normal user or developer. Closing.
