### ISSUE TITLE
Search hotkey activates without using hold key

### ISSUE THREAD

**Issue by carbon-steel** [jchang504/keeptabs#34]
Go to google and use the usual hotkey to activate the search tab functionality (_holdkey_ + /). Then, exit out of the new search tab and the go back to the google tab from before. If you press / without holding down the _holdkey_, then the search tab will open, which is not supposed to happen.

**Comment by carbon-steel** [comment]
This is an issue because, if our extension makes pages behave strangely (even occasionally), then people won't want to use our extension given that a page with something important could malfunction.

**Comment by jchang504** [comment]
This is just #16, a P0 bug that will get fixed before publishing.
