### ISSUE TITLE
Popup does not look right sometimes

### ISSUE THREAD

**Issue by carbon-steel** [jchang504/keeptabs#36]
![image](https://cloud.githubusercontent.com/assets/7697639/26775889/e1bf3328-4a11-11e7-952d-b59c3541f32c.png)

Sometimes, when you click for the popup, this happens. At the time, I had quite a few tabs open. I'm not sure why this happens. I imagine it's some kind of race condition with the rendering.... Perhaps setting some min-widths/min-heights can help.

**Comment by jchang504** [comment]
I think I may have seen this happen with other extension popups before -- probably a Chrome bug. In any case, the popup now shows the options page so if it was specific to our tab search page, it should be gone.
