### ISSUE TITLE
Tab titles should have a max length in the pop-up 

### ISSUE THREAD

**Issue by maxinepqk** [jchang504/keeptabs#37]
Tabs that have really long titles are annoying to scroll through in the pop-up window. We should set a maximum length for tab titles so it hides the rest of the title after it exceeds the maximum length. The user can have an option to expand the entire title if they want to.

![image](https://cloud.githubusercontent.com/assets/7968818/26779172/e8db4ebc-4a16-11e7-9709-e8f437105fdd.png)

**Comment by jchang504** [comment]
Lol this is an abuse of `<title>` on the part of the website developer, but agree. Dunno about expanding because we already have click to select, so it would be tricky to use a button for expand. I think if we make the limit around 2 lines on this size it should be enough 99% of the time.

**Comment by maxinepqk** [comment]
We decided not to do the expansion option (yet).

**Comment by jchang504** [comment]
Closed by 3d87b14180caaade315eae3203cb87a55c23049d.
