### ISSUE TITLE
Add a new tab hotkey

### ISSUE THREAD

**Issue by jchang504** [jchang504/keeptabs#38]
I've been using a standard hotkey mapped to chrome://newtab, but this gets deduplicated to other chrome:// pages when I have them open. It should be a proper built-in hotkey anyway.

**Comment by carbon-steel** [comment]
Why do we want this functionality in our extension? There already is a native hotkey for this purpose that pretty much all of our users will already be used to using. It may be a bit excessive in this case, but I would prefer to fight against feature creep. This specific feature is not a big deal, but this feature is in the neighborhood where I would start wondering if it really should be added or not.

**Comment by jchang504** [comment]
The native shortcuts are not so bad on Mac with Cmd, but on Windows ctrl is very inaccessible. Pressing ctrl+t is strenuous for my hands and not as quick as a KeepTabs-based (i.e., for me, escape-based) htokey.

KeepTabs itself is geared towards users seeking efficiency that are willing to put in some learning to achieve it. Even just getting used to hitting Esc+g to get to Gmail instead of ctrl+t: gm+Enter requires breaking a habit. It's not enormously difficult, but it already has that barrier of effort. I think it's actually easier to learn if everything transfers over with it -- including the shortcuts for closing and creating new tabs. Then, the user is transferring their behavior to a completely new system, rather than being split between two independent shortcut systems they have to work with. This is how I've come to think about using KeepTabs, since I use the tab close hotkey and my hack version of new tab instead of ctrl+w, crtl+t respectively.

Additionally, we already have hotkeys for left-right nav, tab close, and even moving tabs. All but the last of those have native shortcuts, but KeepTabs provides a more easily accessible (and in the future, customizable) version of them. A new tab hotkey completes the basic set of tab management shortcuts and allows the user to fully use KeepTabs instead of the native shortcuts.

If we need to have a further discussion we should probably do so offline.

**Comment by carbon-steel** [comment]
Ok. Well, if we're going to have Keeptabs as an entirely independent and separate system, why don't we add a refresh hotkey as well? However, I do worry that that making this functionality and the new tab functionality be a native part of our extension will limit use up hotkey characters (like 't' or 'r') that users would want to use for actual websites.

**Comment by jchang504** [comment]
Yeah, I was thinking of making new tab not an alphabetic character but something around the punctuation area along with left-right nav and close, like `'` or `,` or something. Ideally all the built-in hotkeys should be customizable as mentioned in #33.

I didn't think of refresh as I don't use it that often. It does bring up a good question of how many native shortcuts we should cover. I definitely think as a guiding principle we can remember that the scope of our extension is limited to tab management, so it's not going to cover ctrl+f, ctrl+p, etc. But since ctrl+t and ctrl+w are explicitly tied to tabs, and also used extremely often (ergonomics benefit) and in particular used in close conjunction with tab navigation (which the user would be using KT for, so it's good to not have to switch to a different modifier key), they make sense to cover. As for refresh, it's borderline for me. I don't use it that often, so I don't mind moving over to hit ctrl. It certainly wouldn't hurt to have it as an option (that can always be disabled) if we implement fully customizable built-in hotkeys -- then the user can essentially choose to what degree they want to go "all in" with KeepTabs: from the one end of only using it for website hotkeys and continuing to use ctrl+t, ctrl+w, etc. to using KT's version of all tab-related native shortcuts.

**Comment by carbon-steel** [comment]
I like the idea of using "." as the new tab hotkey because period is an easy and often used key and this functionality should be the same. Furthermore, I like the idea of using the comma, period, and slash as built-in hotkeys since they're all next to each other.

**Comment by carbon-steel** [comment]
Done by b160a03da603bc08372015cc6310606543bdb463
