### ISSUE TITLE
Implement a method for switching between tabs matching the same hotkey

### ISSUE THREAD

**Issue by jchang504** [jchang504/keeptabs#40]
This should probably be implemented alongside #24, which is related. Even when that's fixed, we still want to be able to switch between tabs matching the same URL, e.g. two YouTube pages. I'm thinking repeated presses of the same hotkey (in sequence) could cycle through all tabs matching that hotkey. Edge case: when you're already on a tab matching that hotkey, you should probably skip that one since obviously the user does not intend to switch to the tab they're already on.

**Comment by carbon-steel** [comment]
Closed by 110bda0efc91

**Comment by carbon-steel** [comment]
Patched by c47e5d1458b4c83637092c7a1043d7d8d724e2d4
