### ISSUE TITLE
Auto-detect operating system and adjust hold key options

### ISSUE THREAD

**Issue by jchang504** [jchang504/keeptabs#43]
For example, remove the `ContextMenu` option (the context menu key only appears on non-Mac keyboards -- and not even on all of them) when the user is on a Mac, and label the `Meta` value as Cmd for Mac, Windows key for Windows. Parsing the output of [this](https://developer.chrome.com/extensions/runtime#method-getPlatformInfo) seems to be the way to do it.

**Comment by carbon-steel** [comment]
I think this is a little more important than P3 because the current interface is a little confusing with the parentheticals in choosing the hold key.

**Comment by jchang504** [comment]
Can we alternatively fix that by just improving the clarity of the UI for now? I have #20 marked as part of the release milestone, so we are definitely going to overhaul the options page UI.

**Comment by jchang504** [comment]
Now that the [new approach](https://github.com/jchang504/keeptabs/issues/15#issuecomment-315638595) to handling the hold key is going to be implemented, this auto-detection (and setting the hold key to a OS-specific default) is now much more important, because some of the hold key choices are terrible for certain OSes. In fact, we should maybe just force the hold key choice and only make it customizable in advanced/experimental settings (#49).
