### ISSUE TITLE
Implement over-screen hold key status + hotkey entry indicator

### ISSUE THREAD

**Issue by jchang504** [jchang504/keeptabs#48]
As a pseudo-solution to #15, we've decided to add a UI element that appears whenever KT thinks the hold key is down. This serves several purposes:

1. Indicates when KT thinks the hold key is down: so when it gets stuck (#15), at least the user can clearly see it and it should be relatively intuitive to press and release the hold key again to fix it.
2. Displays hotkeys as they’re typed: makes multi-character hotkeys easier to use; makes clearer why nothing happened if the user mistypes a hotkey.
3. Makes KT have a visible, tangible element: overall clearer and less intimidating to use, particularly for new users.

It will set us up well for an over-screen tab search UI (#27) as well.

**Comment by carbon-steel** [comment]
I understand that the visual overlay is not done yet. I just want to mention that, with my larger screen size, my eyes don't immediately see the overlay when it appears. I suggest that we make the overlay have some color that pops more and that we make it bigger.
