### ISSUE TITLE
Enable up/down selection in tab search

### ISSUE THREAD

**Issue by jchang504** [jchang504/keeptabs#9]
The simplicity of pressing enter to navigate to the first (highlighted) result in tab search is nice. But if there are a lot of similarly-titled tabs, the user might not be able to easily disambiguate them with search keywords; in this case, it would be useful and intuitive for the user to change the selected (highlighted) tab with the up/down arrow keys.

**Comment by jchang504** [comment]
I realized while refactoring that you can actually click one of the list options to choose it (and I preserved this functionality). But I think up/down selection with keys would fit better with the spirit of KeepTabs.

**Comment by carbon-steel** [comment]
The up and down functionality works with bdaeeb068511fc84bdc5983d0976802209028b3a. However, if you go down too far, you can't see what you're highlighting anymore. Am working to fix that.
